browsers: chrome, firefox, ie
tags: Ad #tags are comma separated and should not be prefixed with a '@' symbol
grid_results_path: /Users
execution_threshold: 3600 #seconds
hub_ip_address: 192.168.0.1
hub_port_number: 4444